/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UiRouteImport } from './routes/ui'
import { Route as SsoCallbackRouteImport } from './routes/sso-callback'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedSuppliersRouteImport } from './routes/_authed/suppliers'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedInvoiceLinesRouteImport } from './routes/_authed/invoice-lines'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as AuthedSettingsSpendTreesRouteImport } from './routes/_authed/settings/spend-trees'
import { Route as AuthedSettingsProfileRouteImport } from './routes/_authed/settings/profile'
import { Route as AuthedSettingsOrganizationRouteImport } from './routes/_authed/settings/organization'
import { Route as AuthedSettingsCompaniesRouteImport } from './routes/_authed/settings/companies'
import { Route as AuthedSettingsCompaniesIndexRouteImport } from './routes/_authed/settings/companies.index'
import { Route as AuthedSettingsCompaniesCompanyIdAccountsRouteImport } from './routes/_authed/settings/companies.$companyId.accounts'

const UiRoute = UiRouteImport.update({
  id: '/ui',
  path: '/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSuppliersRoute = AuthedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInvoiceLinesRoute = AuthedInvoiceLinesRouteImport.update({
  id: '/invoice-lines',
  path: '/invoice-lines',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsSpendTreesRoute =
  AuthedSettingsSpendTreesRouteImport.update({
    id: '/spend-trees',
    path: '/spend-trees',
    getParentRoute: () => AuthedSettingsRoute,
  } as any)
const AuthedSettingsProfileRoute = AuthedSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsOrganizationRoute =
  AuthedSettingsOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => AuthedSettingsRoute,
  } as any)
const AuthedSettingsCompaniesRoute = AuthedSettingsCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsCompaniesIndexRoute =
  AuthedSettingsCompaniesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedSettingsCompaniesRoute,
  } as any)
const AuthedSettingsCompaniesCompanyIdAccountsRoute =
  AuthedSettingsCompaniesCompanyIdAccountsRouteImport.update({
    id: '/$companyId/accounts',
    path: '/$companyId/accounts',
    getParentRoute: () => AuthedSettingsCompaniesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/sign-in': typeof SignInRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/ui': typeof UiRoute
  '/invoice-lines': typeof AuthedInvoiceLinesRoute
  '/settings': typeof AuthedSettingsRouteWithChildren
  '/suppliers': typeof AuthedSuppliersRoute
  '/settings/companies': typeof AuthedSettingsCompaniesRouteWithChildren
  '/settings/organization': typeof AuthedSettingsOrganizationRoute
  '/settings/profile': typeof AuthedSettingsProfileRoute
  '/settings/spend-trees': typeof AuthedSettingsSpendTreesRoute
  '/settings/': typeof AuthedSettingsIndexRoute
  '/settings/companies/': typeof AuthedSettingsCompaniesIndexRoute
  '/settings/companies/$companyId/accounts': typeof AuthedSettingsCompaniesCompanyIdAccountsRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/ui': typeof UiRoute
  '/invoice-lines': typeof AuthedInvoiceLinesRoute
  '/suppliers': typeof AuthedSuppliersRoute
  '/': typeof AuthedIndexRoute
  '/settings/organization': typeof AuthedSettingsOrganizationRoute
  '/settings/profile': typeof AuthedSettingsProfileRoute
  '/settings/spend-trees': typeof AuthedSettingsSpendTreesRoute
  '/settings': typeof AuthedSettingsIndexRoute
  '/settings/companies': typeof AuthedSettingsCompaniesIndexRoute
  '/settings/companies/$companyId/accounts': typeof AuthedSettingsCompaniesCompanyIdAccountsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/ui': typeof UiRoute
  '/_authed/invoice-lines': typeof AuthedInvoiceLinesRoute
  '/_authed/settings': typeof AuthedSettingsRouteWithChildren
  '/_authed/suppliers': typeof AuthedSuppliersRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/settings/companies': typeof AuthedSettingsCompaniesRouteWithChildren
  '/_authed/settings/organization': typeof AuthedSettingsOrganizationRoute
  '/_authed/settings/profile': typeof AuthedSettingsProfileRoute
  '/_authed/settings/spend-trees': typeof AuthedSettingsSpendTreesRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
  '/_authed/settings/companies/': typeof AuthedSettingsCompaniesIndexRoute
  '/_authed/settings/companies/$companyId/accounts': typeof AuthedSettingsCompaniesCompanyIdAccountsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sso-callback'
    | '/ui'
    | '/invoice-lines'
    | '/settings'
    | '/suppliers'
    | '/settings/companies'
    | '/settings/organization'
    | '/settings/profile'
    | '/settings/spend-trees'
    | '/settings/'
    | '/settings/companies/'
    | '/settings/companies/$companyId/accounts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sso-callback'
    | '/ui'
    | '/invoice-lines'
    | '/suppliers'
    | '/'
    | '/settings/organization'
    | '/settings/profile'
    | '/settings/spend-trees'
    | '/settings'
    | '/settings/companies'
    | '/settings/companies/$companyId/accounts'
  id:
    | '__root__'
    | '/_authed'
    | '/sign-in'
    | '/sso-callback'
    | '/ui'
    | '/_authed/invoice-lines'
    | '/_authed/settings'
    | '/_authed/suppliers'
    | '/_authed/'
    | '/_authed/settings/companies'
    | '/_authed/settings/organization'
    | '/_authed/settings/profile'
    | '/_authed/settings/spend-trees'
    | '/_authed/settings/'
    | '/_authed/settings/companies/'
    | '/_authed/settings/companies/$companyId/accounts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  SignInRoute: typeof SignInRoute
  SsoCallbackRoute: typeof SsoCallbackRoute
  UiRoute: typeof UiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ui': {
      id: '/ui'
      path: '/ui'
      fullPath: '/ui'
      preLoaderRoute: typeof UiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/suppliers': {
      id: '/_authed/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthedSuppliersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/invoice-lines': {
      id: '/_authed/invoice-lines'
      path: '/invoice-lines'
      fullPath: '/invoice-lines'
      preLoaderRoute: typeof AuthedInvoiceLinesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/spend-trees': {
      id: '/_authed/settings/spend-trees'
      path: '/spend-trees'
      fullPath: '/settings/spend-trees'
      preLoaderRoute: typeof AuthedSettingsSpendTreesRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/profile': {
      id: '/_authed/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthedSettingsProfileRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/organization': {
      id: '/_authed/settings/organization'
      path: '/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof AuthedSettingsOrganizationRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/companies': {
      id: '/_authed/settings/companies'
      path: '/companies'
      fullPath: '/settings/companies'
      preLoaderRoute: typeof AuthedSettingsCompaniesRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/companies/': {
      id: '/_authed/settings/companies/'
      path: '/'
      fullPath: '/settings/companies/'
      preLoaderRoute: typeof AuthedSettingsCompaniesIndexRouteImport
      parentRoute: typeof AuthedSettingsCompaniesRoute
    }
    '/_authed/settings/companies/$companyId/accounts': {
      id: '/_authed/settings/companies/$companyId/accounts'
      path: '/$companyId/accounts'
      fullPath: '/settings/companies/$companyId/accounts'
      preLoaderRoute: typeof AuthedSettingsCompaniesCompanyIdAccountsRouteImport
      parentRoute: typeof AuthedSettingsCompaniesRoute
    }
  }
}

interface AuthedSettingsCompaniesRouteChildren {
  AuthedSettingsCompaniesIndexRoute: typeof AuthedSettingsCompaniesIndexRoute
  AuthedSettingsCompaniesCompanyIdAccountsRoute: typeof AuthedSettingsCompaniesCompanyIdAccountsRoute
}

const AuthedSettingsCompaniesRouteChildren: AuthedSettingsCompaniesRouteChildren =
  {
    AuthedSettingsCompaniesIndexRoute: AuthedSettingsCompaniesIndexRoute,
    AuthedSettingsCompaniesCompanyIdAccountsRoute:
      AuthedSettingsCompaniesCompanyIdAccountsRoute,
  }

const AuthedSettingsCompaniesRouteWithChildren =
  AuthedSettingsCompaniesRoute._addFileChildren(
    AuthedSettingsCompaniesRouteChildren,
  )

interface AuthedSettingsRouteChildren {
  AuthedSettingsCompaniesRoute: typeof AuthedSettingsCompaniesRouteWithChildren
  AuthedSettingsOrganizationRoute: typeof AuthedSettingsOrganizationRoute
  AuthedSettingsProfileRoute: typeof AuthedSettingsProfileRoute
  AuthedSettingsSpendTreesRoute: typeof AuthedSettingsSpendTreesRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
}

const AuthedSettingsRouteChildren: AuthedSettingsRouteChildren = {
  AuthedSettingsCompaniesRoute: AuthedSettingsCompaniesRouteWithChildren,
  AuthedSettingsOrganizationRoute: AuthedSettingsOrganizationRoute,
  AuthedSettingsProfileRoute: AuthedSettingsProfileRoute,
  AuthedSettingsSpendTreesRoute: AuthedSettingsSpendTreesRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
}

const AuthedSettingsRouteWithChildren = AuthedSettingsRoute._addFileChildren(
  AuthedSettingsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedInvoiceLinesRoute: typeof AuthedInvoiceLinesRoute
  AuthedSettingsRoute: typeof AuthedSettingsRouteWithChildren
  AuthedSuppliersRoute: typeof AuthedSuppliersRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedInvoiceLinesRoute: AuthedInvoiceLinesRoute,
  AuthedSettingsRoute: AuthedSettingsRouteWithChildren,
  AuthedSuppliersRoute: AuthedSuppliersRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  SignInRoute: SignInRoute,
  SsoCallbackRoute: SsoCallbackRoute,
  UiRoute: UiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
